server:
  # 服务端口号
  port: 9797
# 日志配置
logging:
  level:
    root: warn
spring:
  # 应用名称
  application:
    name: NEXUS
  # 上传文件配置
  servlet:
    multipart:
      # 单个最大文件大小
      max-file-size: 30MB
      # 总体文件最大请求大小
      max-request-size: 100MB
  data:
    # redis配置
    redis:
      database: 3
      host: 127.0.0.1
      password:
      port: 6379
      timeout: 5000
      lettuce:
        pool:
          #连接池最大连接数（使用负值表示没有限制），默认8
          max-active: 12
          #连接池最大阻塞等待时间（使用负值表示没有限制），默认-1
          max-wait: -1
          # 连接池中的最大空闲连接，默认8
          max-idle: 8
          # 连接池中的最小空闲连接，默认0
          min-idle: 0
  # 数据库配置(Druid)
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/nexus?userUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: password
      # 初始连接数
      initial-size: 1
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 100
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 100000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 100000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: false
      #安全配置
      stat-view-servlet:
        enabled: false
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: password
      # 过滤配置
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/xml/*.xml


security:
  # Redis用户登录缓存配置
  user-cache-time: 21600
  secret-key:
    token-secret: GhGhg9DG48BfZ3a
    rsa:
      private-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAKuUBGBpKiWGxkV2nkCgb7B43I4mZKvh9R31L+9REaHcAhqq5ZKJvmUcPmTi5G7GyhocFUHKgJpUF9mSfgifpBg4rKAadEW3Jincy22Y2PlQzwNsdw+ld/vRg5W430s8RJ67NwaZ59NyEngiGv2HBXMZn+lTpmXRGinnGMt2Tem7AgMBAAECgYAuycjdv5/aJuQHij7Ccd2zOmouq2KViqMsnbGKKcnMoTHDsumyqbRNX0PWgBb57GStdQ4I6F9kdl0gnDWZRWtaKv/CP7Il5W/T5RrOmspLJ7YBLF9fp7++sF0iUKp6+c/W01OW/TsVwEbYAZ3vsHORmzCzLfK/saW3J8H62AIzcQJBAN/8LjmpkT4fxFPv6rTqNaFogoXniQby98BPkUDlH/esHXnWX/PLAuNLkmexDiaJnxAM3fxOVU/B1ODD4/VGdUsCQQDEGjhuLt/wbkBkZhVV16jnzP8xtp/HRjCJN1wSqb/UhDZZrE7xUKXolxBZ6vGy9duTVfHxFvb+raxN35QDkUdRAkBBXQFMWHyHKZQMfqX6l6KA8NOuKewl9/9uwol766FRkIulg3bK2UKFfAdEdTnQ6zZc47RgLafdt43c7a13ZVFTAkEAjfRxHwmdn/0fbc4b6a0Yntvda85IcUdVAS9q3jO1IpCmi1lZOARqZSldc8nINwUUct5HKn+2QnvT+/c5vS9gUQJBALVYGiIvAT0itvkSCFKn/zz+uKSDI9spL7OkmWM7BWvbp3Q+IgyETYydHTvjHA7cURKagrZaXPCwz+mHvMnjChg=
      public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrlARgaSolhsZFdp5AoG+weNyOJmSr4fUd9S/vURGh3AIaquWSib5lHD5k4uRuxsoaHBVByoCaVBfZkn4In6QYOKygGnRFtyYp3MttmNj5UM8DbHcPpXf70YOVuN9LPESeuzcGmefTchJ4Ihr9hwVzGZ/pU6Zl0Rop5xjLdk3puwIDAQAB
  jwt:
    # 是否限制单用户登录
    single-login: false
    # token存放请求头
    header: Authorization
    # 令牌前缀
    token-start-with: Bearer
    # AccessToken令牌过期时间, 单位分钟，默认两小时
    access-expiration-time: 120
    # RefreshToken令牌过期时间, 单位分钟，默认14天
    refresh-expiration-time: 20160
    # 在线用户key
    online-key: online-token-
    # 是否开启自动续签
    delay-token: false
    # token 续期检查时间范围（默认30分钟，单位默认毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
    detect: 1800000
    # 续期时间范围，默认 1小时，这里单位毫秒
    renew: 3600000